name: 'GitHub Workflows'
description: 'Run a set of GitHub api workflow instructions'
author: jpshrader
inputs:
  instructions:
    description: 'String/Path of Github Workflow instructions'
    type: string
    required: true
  access_token:
    description: 'GitHub Api Access Token'
    type: string
    required: true

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
      with:
        repository: jpshrader/github-workflows
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'yarn'
    - name: yarn install
      shell: bash
      run: yarn install
    - name: Run application
      shell: bash
      run: yarn start --access_token ${{ inputs.access_token }} --instructions "${{ inputs.instructions }}"
