name: 'GitHub Workflows'
description: 'Run a set of GitHub api workflow instructions'
author: jpshrader
inputs:
  instructions:
    description: 'List of instructions for Github api workflows to run'
    type: string
    required: true
  file_type:
    description: 'Type of file being read in'
    type: string
    required: true
  access_token:
    description: 'GitHub Api Access Token'
    type: string
    required: true

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
      with:
        repository: jpshrader/github-workflows
        path: github-workflows
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r ./github-workflows/requirements.txt
    - name: Run application
      shell: bash
      run: |
        python ./github-workflows/main.py --instructions ${{ inputs.instructions }} --file_type ${{ inputs.file_type }} --access_token ${{ inputs.access_token }} --base_path ./github-workflows/
