name: GitHub Workflows
description: 'Run a set of GitHub api workflow instructions'
author: jpshrader
inputs:
  artifact_name:
    description: 'Name of the file artifact in stored in Github'
    required: true
  file_name:
    description: 'Name of the file contained in the Github Artifact'
    required: true
  access_token:
    description: 'GitHub Api Access Token'
    required: true

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
      with:
        repository: jpshrader/github-workflows

    - name: setup node
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'yarn'

    - name: yarn install
      shell: bash
      run: yarn install

    - name: Download instructions file
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.artifact_name }}

    - name: Run application
      shell: bash
      run: yarn start --instructions ${{ inputs.file_name }} --access_token ${{ inputs.access_token }}
